# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
xcode_sdk: iphonesimulator13.2
language: swift
cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example

jobs:
    include:
# - stage: compile
#      script: set -o pipefail && xcodebuild build -workspace Example/Sakai-Example.xcworkspace -scheme Sakai-Example -sdk iphonesimulator11.3 ONLY_ACTIVE_ARCH=NO | xcpretty
    - stage: test
      script: set -o pipefail && xcodebuild test -enableCodeCoverage YES -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11' -workspace Example/Sakai-Example.xcworkspace -scheme Sakai-Example | xcpretty -c
      after_success: bash <(curl -s https://codecov.io/bash) -Z -X s3 -t $CODECOV_TOKEN
